---
title: CV
name: Caitie
surname: Reza
position: "Masters Student"
address: "Bren School of Environmental Science & Managment, University of California Santa Barbara"
phone: +1 661 666 1356
www: https://caitiereza.github.io/244_website/
email: "caitlinreza@ucsb.edu"
github: https://github.com/CaitieReza/
linkedin: https://www.linkedin.com/in/caitie-reza-50b8a7115/
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Hi"
output: 
  vitae::markdowncv:
    theme: kjhealy
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

## gg

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

## Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Masters of Environmental Science and Management", "2020-22", "The Bren School, UCSB", "Santa Barbara, California",
  "Bachelors in Zoology", "2019", "Michigan State University", "East Lansing, Michigan",
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

## Research Experience

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

## Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

